$(function(){
    $(".two").css("display","none")
    $(".thress").css("display","none")
    $("#noticepoint").on('click',function(){
        console.log(7777)
        $(".Curtain").css("display","block")
        $(".daio_box").css("display","block")
        $(".btn_one_content").addClass('active');
        $(".btn_two_content").removeClass('active');
        $(".btn_three_conent").removeClass('active');
    })
    $(".close").on('click',function(){
        $(".daio_box").css("display","none")
        $(".Curtain").css("display","none")
        $(".one").css("display",'block');
        $(".two").css("display","none")
        $(".thress").css("display","none")
        $(".btn_one_content").removeClass('active');
        $(".btn_two_content").removeClass('active');
        $(".btn_three_conent").removeClass('active');
    })
    $(".btn_one_content").on('click',function(){
        $(".one").css("display","block")
        $(".two").css("display","none")
        $(".thress").css("display","none")
        $(".btn_one_content").addClass('active');
        $(".btn_two_content").removeClass('active');
        $(".btn_three_conent").removeClass('active');
    })
    $(".btn_two_content").on('click',function(){
        $(".two").css("display",'block');
        $(".one").css("display","none")
        $(".thress").css("display","none")
        $(".btn_two_content").addClass('active');
        $(".btn_one_content").removeClass('active');
        $(".btn_three_conent").removeClass('active');
    })
    $(".btn_three_conent").on('click',function(){
        $(".thress").css("display",'block');
        $(".one").css("display","none")
        $(".two").css("display","none")
        $(".btn_three_conent").addClass('active');
        $(".btn_one_content").removeClass('active');
        $(".btn_two_content").removeClass('active');
      
    })
    $('.one_button').on('click',function(){
        $(".daio_box").css("display","none")
        $(".Curtain").css("display","none")
    })
})